[profile.default]
src = "src"
out = "out"
libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    #
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]
via_ir = false
optimizer = true
optimizer_runs = 20000

# Add fs permissions for the deployments directory
fs_permissions = [{ access = "read-write", path = "./deployments"}]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    #
    # To remedy this, we'll remap the ds-test and forge-std imports to our own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std/src/',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/contracts/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/contracts/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

[profile.deploy]
src = "src"
out = "out"
libs = [
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]
via_ir = true
optimizer = true
optimizer_runs = 5

[rpc_endpoints]
testnet = "${TESTNET_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[fmt]
line_length = 140
tab_width = 4
bracket_spacing = true